# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1234.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 720)
        MainWindow.setStyleSheet("background-color: #F8F8FF;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_1 = QtWidgets.QLabel(self.centralwidget)
        self.image_1.setGeometry(QtCore.QRect(0, 330, 311, 341))
        self.image_1.setText("")
        self.image_1.setPixmap(QtGui.QPixmap("Desktop/prog/face/image_review_2.png"))
        self.image_1.setScaledContents(True)
        self.image_1.setObjectName("image_1")
        self.image_2 = QtWidgets.QLabel(self.centralwidget)
        self.image_2.setGeometry(QtCore.QRect(890, 330, 311, 341))
        self.image_2.setText("")
        self.image_2.setPixmap(QtGui.QPixmap("Desktop/prog/face/image_review_2.png"))
        self.image_2.setScaledContents(True)
        self.image_2.setWordWrap(False)
        self.image_2.setObjectName("image_2")
        self.label_main_name = QtWidgets.QLabel(self.centralwidget)
        self.label_main_name.setGeometry(QtCore.QRect(300, 0, 651, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        self.label_main_name.setFont(font)
        self.label_main_name.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(201, 87, 149, 255), stop:1 rgba(179, 65, 244, 255));")
        self.label_main_name.setObjectName("label_main_name")
        self.brn_final = QtWidgets.QPushButton(self.centralwidget)
        self.brn_final.setGeometry(QtCore.QRect(500, 510, 191, 31))
        self.brn_final.setStyleSheet("QPushButton {\n"
"  border: 2px solid #c15992;\n"
"  border-radius: 5px;\n"
"  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(201, 87, 149, 255), stop:1 rgba(179, 65, 244, 255));\n"
"  color: white;\n"
"  font-weight: bold;\n"
"  padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #c15992;\n"
"}\n"
"")
        self.brn_final.setObjectName("brn_final")
        self.combo_choose = QtWidgets.QComboBox(self.centralwidget)
        self.combo_choose.setGeometry(QtCore.QRect(500, 370, 191, 31))
        self.combo_choose.setStyleSheet(" background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(201, 87, 149, 255), stop:1 rgba(179, 65, 244, 255));\n"
"border: 1px;\n"
"border-radius: 5px;\n"
"color: white;")
        self.combo_choose.setObjectName("combo_choose")
        self.btn_image1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_image1.setGeometry(QtCore.QRect(0, 300, 311, 41))
        self.btn_image1.setStyleSheet("QPushButton {\n"
"  border: 2px solid #c15992;\n"
"  border-radius: 5px;\n"
"  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(201, 87, 149, 255), stop:1 rgba(179, 65, 244, 255));\n"
"  color: #FFFFFF;\n"
"  font-weight: bold;\n"
"  padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #c15992;\n"
"}\n"
"")
        self.btn_image1.setObjectName("btn_image1")
        self.btn_image2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_image2.setGeometry(QtCore.QRect(890, 300, 311, 41))
        self.btn_image2.setStyleSheet("QPushButton {\n"
"  border: 2px solid #c15992;\n"
"  border-radius: 5px;\n"
"  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(201, 87, 149, 255), stop:1 rgba(179, 65, 244, 255));\n"
"  color: white;\n"
"  font-weight: bold;\n"
"  padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #c15992;\n"
"}\n"
"")
        self.btn_image2.setObjectName("btn_image2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        font = QtGui.QFont()
        font.setItalic(True)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_main_name.setText(_translate("MainWindow", "Проверить сходство лица и многое прочее"))
        self.brn_final.setText(_translate("MainWindow", "Проверить"))
        self.btn_image1.setText(_translate("MainWindow", "Загрузить фото"))
        self.btn_image2.setText(_translate("MainWindow", "Загрузить фото"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.menu_2.setTitle(_translate("MainWindow", "Выход"))
        self.action.setText(_translate("MainWindow", "Информация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
